server:
  port: 9600

# 数据源配置
spring:
  application:
    name: manager-service

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: manager-service  #客户端服务名
    instance-id: manager-service:9600 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      # 单机 defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://${eureka.instance.hostname}:9500/eureka/ #注册中心的地址
